// Generated by CoffeeScript 1.9.3
(function() {
  $(function() {
    var AppView, appView;
    AppView = Backbone.View.extend({
      el: '#container',
      template: _.template($("#template0").html()),
      initialize: function() {
        return this.render();
      },
      render: function() {
        var vars;
        vars = {
          label_var: "set in backbone template"
        };
        return this.$el.html(this.template(vars));
      }
    });
    return appView = new AppView();
  });

}).call(this);
