// Generated by CoffeeScript 1.9.3
(function() {
  $(function() {
    var app;
    app = {};
    app.Todo = Backbone.Model.extend({
      defaults: {
        title: "",
        completed: false
      }
    });
    app.TodoList = Backbone.Collection.extend({
      model: app.Todo,
      localStorage: new Backbone.LocalStorage("backbone-todo")
    });
    app.todoList = new app.TodoList();
    app.TodoView = Backbone.View.extend({
      tagName: "li",
      template: _.template($("#item-template").html()),
      render: function() {
        return this.$el.html(this.template(this.model.toJSON()));
      }
    });
    app.AppView = Backbone.View.extend({
      el: "#todoapp",
      initialize: function() {
        this.input = this.$("#new-todo");
        app.todoList.on("add", this.addOne, this);
        return app.todoList.fetch();
      },
      addOne: function(todo) {
        var view;
        view = new app.TodoView({
          model: todo
        });
        view.render();
        return $("#todo-list").append(view.$el);
      },
      events: {
        "keypress #new-todo": "createTodoOnEnter",
        "change .toggle": "toggleCompletion"
      },
      createTodoOnEnter: function(e) {
        if (e.which !== 13 || this.input.val().trim() === "") {
          return;
        }
        app.todoList.create(this.newAttributes());
        return this.input.val("");
      },
      newAttributes: function() {
        return {
          title: this.input.val(),
          completed: false
        };
      },
      toggleCompletion: function() {}
    });
    return app.appView = new app.AppView();
  });

}).call(this);
